### ISSUE TITLE
Fix outstanding TODOs from cleanups

### ISSUE THREAD

**Issue by adamcik** [mopidy/pyspotify#106]
Summary of the most relevant cleanup TODOs that are outstanding:

- [ ] Remove casts in ``*_SP_*`` macros so compiler can type check "everything"
- [ ] Make code py_size_t clean
- [ ] Switch to a generic linked list for callback handling and/or switch to returning a callback id used for removing callbacks. Last known place we are leaking memory.
- [ ] Fix NULL deference cases and other places like malloc where we should be checking for errors.
- [ ] Add region country code sanity checks
- [ ] Handle NULLs inside the loops that convert artists, tracks etc to python lists.

**Comment by jodal** [comment]
Due to the imminent release of the 2.0 rewrite of pyspotify, this will probably never be done. Closing.
