### ISSUE TITLE
Jukebox hangs after certain sequences

### ISSUE THREAD

**Issue by ZenithDK** [mopidy/pyspotify#114]
Provided that you have a the appkey in the dir with the jukebox.py application and a playlist with at least 2 tracks on it, I can make the jukebox hang using the following examples:
```
play 0 1
queue 0 2
next
stop
quit -> hang

queue 0 1
queue 0 2
next -> playing!
next
quit -> hang

queue 0 1
stop
queue 0 2
next
quit -> hang

play 0 1
play 0 2
stop
quit -> hang
```

**Comment by jodal** [comment]
Due to the imminent release of the 2.0 rewrite of pyspotify, this will probably never be done. Closing.
