### ISSUE TITLE
deb packaged version for version 2

### ISSUE THREAD

**Issue by rodrigoaguilera** [mopidy/pyspotify#146]
as with 1.11 can be installed this way
http://docs.mopidy.com/en/latest/installation/debian/
can the newest version be installed the same way?

**Comment by jodal** [comment]
An initial version of the Debian package is now available in the v2.x/debian branch. I'll publish binary packages at apt.mopidy.com when Mopidy-Spotify 2 is ready as well.

**Comment by jodal** [comment]
The v2.x/debian branch is now up to date with pyspotify 2.0.0. Making and releasing a Debian package is currently blocked on the availability of a Debian package of cffi >= 1.0. I've asked the maintainer if he has an experimental package I can test with.

**Comment by jodal** [comment]
Debian packages of pyspotify 2 have been available from apt.mopidy.com since at least August 18, I've simply forgotten to close this issue.
