### ISSUE TITLE
Recursion error, same as in #122

### ISSUE THREAD

**Issue by bphermansson** [mopidy/pyspotify#153]
Hi
I get the recursion error described in https://github.com/mopidy/pyspotify/issues/122 with 2.0.0b4. The fix in that thread seems to help.

**Comment by jodal** [comment]
This has recently surfaced as mopidy/mopidy-spotify#49 too.

**Comment by jodal** [comment]
Currently I can't reproduce this. I could blindly disable the `playlist_update_in_progress` event in the hope of it making sure this never happens again. That doesn't feel like a very good solution, and we'll be left without that event forever.

Thus, I opt to close this issue until it resurfaces again, in the hope of ending up with a better solution then.
