### ISSUE TITLE
Installation problem with debian

### ISSUE THREAD

**Issue by pawnies20** [mopidy/pyspotify#154]
Hi and thanx for spotipy!!!

i have a problem.

after installing spotipy with this documentation:
https://pyspotify.mopidy.com/en/latest/installation/

I obtain this error when i lanch python and the first command:

import spotify

>>> import spotify
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spotify.py", line 5, in <module>
    session = spotify.Session()
AttributeError: 'module' object has no attribute 'Session'

I try to uninstall but...always this error.

Can you help me please?

**Comment by adamcik** [comment]
Did you by any change call your example file `spotify.py`, if so you are likely just importing yourself :-)

Closing under the assumption that this is the case, if not and this looks like a bug in pyspotify feel free to reopen.

**Comment by pawnies20** [comment]
when i launch python command:
and after import spotify

it's the same problem

**Comment by adamcik** [comment]
Is there a file called `spotify.py` in the directory you are testing from? If so rename it to anything else and things should work.

**Comment by tkrpata** [comment]
Just for other people who might be having this issue, double-check for not only a spotify.py but a spotify.pyc as well. Remove/rename these.
