### ISSUE TITLE
Max recursion level exceeded by playlist_update_in_progress callback

### ISSUE THREAD

**Issue by DavisNT** [mopidy/pyspotify#165]
When using pyspotify==2.0.0 with Mopidy==1.0.5 and Mopidy-Spotify==2.0.0 (commit 70f27932cb in develop) Mopidy crashes after some time with stacktrace:

    From cffi callback <function playlist_update_in_progress at 0x383acb0>:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 647, in playlist_update_in_progress
        spotify._session_instance, sp_playlist, add_ref=True)
      File "/usr/local/lib/python2.7/dist-packages/spotify/__init__.py", line 58, in wrapper
        return f(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 47, in _cached
        playlist = Playlist(session, sp_playlist=sp_playlist, add_ref=add_ref)
      File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 68, in __init__
        lib.sp_playlist_add_ref(sp_playlist)
      File "/usr/local/lib/python2.7/dist-packages/spotify/__init__.py", line 57, in wrapper
        with _lock:
      File "/usr/lib/python2.7/threading.py", line 126, in acquire
        self._note("%s.acquire(%s): recursive success", self, blocking)
    RuntimeError: maximum recursion depth exceeded
    From cffi callback <function playlist_update_in_progress at 0x383acb0>:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 647, in playlist_update_in_progress
        spotify._session_instance, sp_playlist, add_ref=True)
      File "/usr/local/lib/python2.7/dist-packages/spotify/__init__.py", line 58, in wrapper
        return f(*args, **kwargs)
      File "/usr/lib/python2.7/threading.py", line 155, in __exit__
        self.release()
      File "/usr/lib/python2.7/threading.py", line 152, in release
        self._note("%s.release(): non-final release", self)
    RuntimeError: maximum recursion depth exceeded
    From cffi callback <function playlist_update_in_progress at 0x383acb0>:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 647, in playlist_update_in_progress
        spotify._session_instance, sp_playlist, add_ref=True)
      File "/usr/local/lib/python2.7/dist-packages/spotify/__init__.py", line 58, in wrapper
        return f(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 47, in _cached
        playlist = Playlist(session, sp_playlist=sp_playlist, add_ref=add_ref)
      File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 68, in __init__
        lib.sp_playlist_add_ref(sp_playlist)
      File "/usr/local/lib/python2.7/dist-packages/spotify/__init__.py", line 57, in wrapper
        with _lock:
    RuntimeError: maximum recursion depth exceeded while calling a Python object
    *** glibc detected *** /usr/bin/python: double free or corruption (!prev): 0x07234860 ***

The problem occurred after playing Spotify and local tracks on Mopidy and afterwards stopping playback and leaving Mopidy running for some hours. This was observed several times ("randomly" without trying to reproduce the issue or understand what caused it). This was the first time this issue happened after enabling logging of Mopidy stdout/stderr to file (the exception/stacktrace is **not** written to Mopidy logfile). This happened on Raspbian (Raspberry Pi model B).

**Comment by jodal** [comment]
This looks like the same issue as in #122 and #153 surfacing again. If someone can narrow down how to reproduce this consistently I'll hopefully be able to fix it.

**Comment by jodal** [comment]
This is potentially fixed by 5a6470d53564529b3b25d519b6632bf1bc010497. Are you able to test with it? `pip install pyspotify==dev` should install a version with that fix.

**Comment by DavisNT** [comment]
Thank you very much! :+1:

I have installed latest Mopidy-Spotify and pyspotify develop versions by: 

    pip install -U https://github.com/mopidy/mopidy-spotify/archive/develop.zip
    pip install -U https://github.com/mopidy/pyspotify/archive/v2.x/develop.zip

`pip install -U pyspotify==dev` had failed for me. I have updated other Python packages to their latest PyPI published versions as well (Mopidy-1.0.7 Mopidy-Dirble-1.1.2 cachetools-1.0.3 humanfriendly-1.29 pyasn1-0.1.8 pyasn1-modules-0.0.6 pyspotify-2.0.0 setuptools-18.0.1). 

I will keep Mopidy running for a few days and let you know. 
Previously when trying Mopidy-Spotify 2.0.0 and pyspotify 2.0.0 Mopidy crashed within a day.

**Comment by jodal** [comment]
We managed to reproduce the issue with this fix in place too. The hunt
continues ☺

**Comment by DavisNT** [comment]
Couldn't there be a bug in libspotify - calling `playlist_update_in_progress()` callback from `sp_playlist_add_ref()` if it is called while processing this callback?

**Comment by jodal** [comment]
I believe commit e06b96a6c6e49e89c9f58778756da8f959129a2e might have fixed this. Please comment if this is not true, and this should be reopened.

**Comment by DavisNT** [comment]
Thank you very much! I will test this and let you know!

**Comment by DavisNT** [comment]
I have experienced some Mopidy crashed while using commit e06b96a6c6e49e89c9f58778756da8f959129a2e. Those crashes did **not** write anything in stdout/stderr or mopidy.log.

**Comment by kingosticks** [comment]
I don't see this particular max recursion error any more. I do still get [segmentation faults during startup](http://dpaste.com/1V93RA5) but they may be due to something else.

**Comment by DavisNT** [comment]
I still get Mopidy crashes without anything written to stdout/stderr or Mopidy logs. I will enable core dumps to get some details.

**Comment by jodal** [comment]
Yeah, ditto. It seems like the max recursion issue is gone, but we have at least one other segfault that we all three have experienced now.

**Comment by kingosticks** [comment]
I get two different ones. One related to starred playlists when my
webclient fetches the list of playlists and one when stopping mopidy and it
tries to log out.

**Comment by jodal** [comment]
Can you open two new issues with all the information you have on them?

**Comment by kingosticks** [comment]
I shall do so when I return from holiday next week.

**Comment by richard-ive** [comment]
Hello!

 

Important message, please visit http://babajiskitchen.com.au/afraid.php?wch

 

richard@xanox.net

**Comment by richard-ive** [comment]
Hello!

 

Important message, please visit http://mitra24.com/outside.php?0

 

richard@xanox.net

**Comment by richard-ive** [comment]
Hello!

 

New message, please read <http://lemonlimelabs.com/seat.php?oaj>

 

richard@xanox.net

**Comment by richard-ive** [comment]
Hello!

 

New message, please read <http://tanstore.com.tr/art.php?8>

 

richard@xanox.net

**Comment by richard-ive** [comment]
Hello!

 

New message, please read <http://beshoper.com/without.php?nry>

 

richard@xanox.net
