### ISSUE TITLE
Spotify Connect integration

### ISSUE THREAD

**Issue by BlackLight** [mopidy/pyspotify#166]
The only last bit, as far as I'm concerned, to have a complete Spotify API would be the integration with the new Spotify Connect feature. Is it on your schedule?

Fabio

**Comment by jodal** [comment]
pyspotify is simply a libspotify wrapper and already covers 100% of the libspotify API. libspotify knows nothing of Spotify Connect, and no longer gets new features, so the answer is no.

So far, Spotify Connect specs and details are only available to Spotify partners. The only alternative I know of is the reverse engineering efforts of https://github.com/sashahilton00/spotify-connect-resources and https://github.com/plietar/spotify-connect.
