### ISSUE TITLE
Choppy sound during playback

### ISSUE THREAD

**Issue by patrickcorrigan** [mopidy/pyspotify#167]
On one of my machines I get choppy playback using this library. I'm trying to figure out why. Any ideas?

**Comment by jodal** [comment]
Du you use one of the included audio sinks, or your own audio data handling?

If an included sink, which one?

What OS do the troubled machine run?

What's the difference between the system where it is choppy and the systems
where it works nicely?

Anything else you can think of that might be relevant to reproduce the
issue?

**Comment by patrickcorrigan** [comment]
I use the AlsaSink. I'm running Arch Linux. The machine that I didn't have trouble with was a Ubuntu 15.04 virtual machine with gnome. 

Here is the output of aplay -l listing playback hardware devices.
```
card 0: PCH [HDA Intel PCH], device 0: CS4206 Analog [CS4206 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 1: CS4206 Digital [CS4206 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
I'm using pyalsaaudio (0.8.2) the latest pyspotify and python 3.4.3

Thank you very much for your quick response. I really appreciate it.

If you would like anymore information just let me know.

**Comment by patrickcorrigan** [comment]
Solved by installing and configuring pulseaudio :)

**Comment by valevalorin** [comment]
I'm having this issue, or a similar one, on my Arch setup. When I try to play the track I just get constant stuttering/skipping multiple times a second. I tried installing and configuring pulseaudio but I think it actually made the problem worse.

ALSA Info:  http://www.alsa-project.org/db/?f=d38a574964a957afda7b43edb75f4daff271832e

I'm using the default examples/play_track.py script for testing.
