### ISSUE TITLE
Question : How to get local file location from 'track' object.

### ISSUE THREAD

**Issue by ezman** [mopidy/pyspotify#169]
How can I get the location of a 'local' track via the 'track' object?

I was hoping there was an attribute on the 'track' object that would allow we to do this. So far I have not been able to work out how to do this.

Any pointers would be greatly appreciated!

Thanks

fasih

**Comment by jodal** [comment]
There's not much documentation of local tracks available from Spotify.
AFAIK there is no path available, just the data that is part of the URI.

https://pyspotify.mopidy.com/en/latest/api/session/#spotify.Session.get_local_track
contains just about all I know about local tracks.
