### ISSUE TITLE
Question about dependencies

### ISSUE THREAD

**Issue by AlexandrePTJ** [mopidy/pyspotify#173]
Hi,

I maintain package for Archlinux and I was wondering if cffi is still required once pyspotify is build.
Or is it only required to make the package ?

**Comment by jodal** [comment]
Currently cffi is required for both building and running the package.

cffi upstream has done some work towards splitting in two packages; cffi and cffi-runtime or similar. Once that is in place, a much smaller dependency is all that is needed at runtime.

**Comment by AlexandrePTJ** [comment]
Ok, thanks.
