### ISSUE TITLE
.deb depends on Python 2.7.5-5, but Debian Wheezy only has 2.7.3

### ISSUE THREAD

**Issue by herrernst** [mopidy/pyspotify#174]
I'm using mopidy on my Raspberry Pi running Raspbian, which is based on Debian wheezy.
I cannot upgrade python-spotify anymore, apt says:
````
The following packages have unmet dependencies:
 python-spotify : Depends: python-cffi but it is not going to be installed
                  Depends: python:any (>= 2.7.5-5~) but it is not installable
````
Is this exact sub-sub-version (x.x.5) of python necessary?
Thanks.

**Comment by jodal** [comment]
You're probably installing packages built for jessie (stable) on wheezy (oldstable). Luckily, the apt.mopidy.com server has pyspotify packages built for both jessie and wheezy.

1. Replace "stable" with "wheezy" in `/etc/apt/sources.list.d/mopidy.list`: `sudo sed -i -e 's/stable/wheezy/' /etc/apt/sources.list.d/mopidy.list
2. Run `sudo apt-get update`
3. Run `sudo apt-get install python-spotify`

(On an aside, Raspbian should get their thing together and release a jessie-based image.)

**Comment by herrernst** [comment]
That was it, thanks for your help.
At Raspbian + Jessie: +1, I'm also waiting.

**Comment by jodal** [comment]
I'm currently updating the pyspotify installation docs to focus on distro packages first, now when pyspotify 2 have been available for a while is starting to get packaged.
