### ISSUE TITLE
Spotify login error

### ISSUE THREAD

**Issue by rasda** [mopidy/pyspotify#176]
hey.

since the last upgrade i get the following error when starting up mopidy.

    2015-09-09 12:07:36,009 ERROR [13420:SpotifyEventLoop] spotify.session: Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
    2015-09-09 12:07:37,449 INFO [13420:SpotifyEventLoop] spotify.session: Spotify logged out

any hints on how to fix that?

thx in advance.

**Comment by jodal** [comment]
"UNABLE_TO_CONTACT_SERVER" is the only hint we have here. If Spotify doesn't have any intermittent issues right now, I'd check your own firewall and network setup.

**Comment by rasda** [comment]
i can ping spotify.com successfully from the commandline of that machine.
i also have a proxy here in my company which i have configured in the "mopidy.conf".
but that seems not to be the issue since i have network access with all other services running there.
as i said before, this started after the last upgrade on monday. before everything was working fine and i did not touch the config.

**Comment by adamcik** [comment]
Sounds like a possible problem in the proxy handling in 2.0 then. As likely you had some 1.x version before the upgrade.

**Comment by rasda** [comment]
i am not sure what version i had before. are there any apt-get logs where i can find that out?

**Comment by adamcik** [comment]
`/var/log/aptitude` or one one the corresponding .gz files should do.

**Comment by rasda** [comment]
ok seems that i had an 1.x version before

    2015-09-07 13:32:57 upgrade mopidy-spotify:all 1.4.0-0mopidy1 2.0.1-0mopidy1
    2015-09-07 13:32:57 upgrade python-spotify:armhf 1.11-0mopidy1 2.0.3-0mopidy1

**Comment by rasda** [comment]
just installed the old versions and i can connect to spotify.

    2015-09-09 13:18:04,969 INFO [14793:SpotifyThread] mopidy_spotify.session_manager: Connected to Spotify

**Comment by jodal** [comment]
What are your proxy settings? Copy-paste the `[proxy]` section from `mopidy deps`.

**Comment by rasda** [comment]
[proxy]
scheme = http
hostname = 172.16.255.254
port = 8080
username = user
password = password

**Comment by rasda** [comment]
when i run ```mopidy deps``` i get the following output:
```
:~# mopidy deps
Executable: /usr/bin/mopidy
Platform: Linux-3.8.13.23-armv7l-with-Ubuntu-14.04-trusty
Python: CPython 2.7.6 from /usr/lib/python2.7
Mopidy: 1.1.0 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  requests: 2.2.1 from /usr/lib/python2.7/dist-packages
  tornado>=2.3: 3.1.1 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify-Tunigo: 0.2.1 from /usr/lib/python2.7/dist-packages
  Mopidy>=0.19.0: 1.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests: 2.2.1 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 3.1.1 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  mopidy-spotify>=1.2.0: 1.4.0 from /usr/share/mopidy
    Mopidy>=1.0: 1.1.0 from /usr/lib/python2.7/dist-packages
      Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
      requests: 2.2.1 from /usr/lib/python2.7/dist-packages
      tornado>=2.3: 3.1.1 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    pyspotify>=1.9,<1.999: 1.11 from /usr/lib/pymodules/python2.7
  tunigo: 0.1.3 from /usr/lib/python2.7/dist-packages
    requests>=2.0.0: 2.2.1 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify: 1.4.0 from /usr/share/mopidy
  Mopidy>=1.0: 1.1.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests: 2.2.1 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 3.1.1 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  pyspotify>=1.9,<1.999: 1.11 from /usr/lib/pymodules/python2.7
GStreamer: 0.10.36.0 from /usr/lib/python2.7/dist-packages/gst-0.10/gst
  Detailed information: 
    Python wrapper: gst-python 0.10.22.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lame
        mad
        mp3parse
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
```

**Comment by jodal** [comment]
Seems I simply forgot to add proxy support when reimplementing Mopidy-Spotify 2.0. I opened a bug in the proper repo to track this: mopidy/mopidy-spotify#68.
