### ISSUE TITLE
Every track is NOT_STREAMABLE: 2

### ISSUE THREAD

**Issue by suBDavis** [mopidy/pyspotify#178]
I have been unable, after 15 or so attempts and many searches, to find a single track that was streamable.  Every single track has `<TrackAvailability.NOT_STREAMABLE: 2>` as it's availability property, and I am really confused about how this is possible.

I have a premium account, and can listen to all of the tracks I've tried through the normal client.  Perhaps you could provide me with a track ID that is known to be streamable for testing purposes?

Every other function I've tried works, but as soon as I try `player.load(track)`  I get `spotify.error.LibError: The track cannot be played`

Thanks!

**Comment by jodal** [comment]
You closed the issue, so I assume you found a solution. Care to share it here in case anyone else has the same problem?

**Comment by suBDavis** [comment]
I've resolved this myself, but it should be noted that you apparently need to close any and all spotify sessions you are logged into normally, then re-authenticate with pyspotify.
