### ISSUE TITLE
Search API has been broken by Spotify

### ISSUE THREAD

**Issue by adamcik** [mopidy/pyspotify#183]
https://github.com/mopidy/mopidy-spotify/issues/89

Best bet is likely to retrofit the new web API within the existing API wrapper to keep things working with minimal external API changes.

**Comment by trygveaa** [comment]
How is the state of login credentials in libspotify vs. the new API?

**Comment by adamcik** [comment]
https://developer.spotify.com/web-api/migration-guide/ has the migration guide for the old metadata API, but it's not clear what parts libspotify uses. I know at least search is effected.

As for the auth story, https://developer.spotify.com/web-api/endpoint-reference/ has the overview. For basic lookups you don't need OAuth, but for playlists and browse you typically do.

**Comment by adamcik** [comment]
Also since this looks like just search for now a workaround should be relatively simple to hack up.

**Comment by adamcik** [comment]
Longer term we probably need to go the route that mopidy-spotify-web has already started down...

**Comment by trygveaa** [comment]
Okay, so the migration guide mentions these new endpoints:

```
/v1/albums/{id}
/v1/artists/{id}
/v1/artists/{id}/albums
/v1/search?q=foo&type=album
/v1/search?q=foo&type=artist
/v1/search?q=foo&type=track
/v1/tracks/{id}
```

From the endpoint reference, none of these require authentication. So we can implement support for these in pyspotify without requiring any additional authentication, so that's at least good.

**Comment by trygveaa** [comment]
For information, this has been fixed for now in Mopidy-Spotify with mopidy/mopidy-spotify#95. It's undecided if we want a fix for this in pyspotify, or to keep pyspotify only as a plain wrapper around libspotify.

**Comment by jodal** [comment]
Just to get it on the record: The scope of the pyspotify project is to be a libspotify wrapper. pyspotify already covers the full libspotify API, and pyspotify is thus a mostly complete project.

Any support for the Spotify Web API is out of scope for the pyspotify project.
