### ISSUE TITLE
Prefetch doesn't seem to work

### ISSUE THREAD

**Issue by theYoursTruly** [mopidy/pyspotify#185]
...or I don't know how to use it.

I have a track that I want to load to memory before playing so it doesn't stop for loading randomly in the middle. What I do is:

```
session.player.prefetch(track);
session.player.load(track);
session.player.play()
```
where _track_ is a loaded `Track` object.

Is it possible to check if track has been pre-fetched? Does it require some preparations (cache settings for example)?

**Comment by jodal** [comment]
https://pyspotify.mopidy.com/en/latest/api/player/#spotify.player.Player.prefetch doesn't tell too much, so I checked the libspotify docs at https://developer.spotify.com/docs/libspotify/12.1.51/group__session.html#gaf42e30a1f430ac7c436c7d9f0485368d:

> Instruct libspotify to start loading of a track into its cache. This could be done by an application just before the current track ends.

In other words, `prefetch()` will just hint to libspotify that we'll be playing this trakc soon, so you might as well start loading it. It will however not block further execution until the entire track is prefetched, so calling `prefetch()` and then immediately `load()` and `play()` will have almost zero effect.

**Comment by theYoursTruly** [comment]
I'll need to create some kind of buffer then. Thanks for help!

Also great library, made my life much easier :)
