### ISSUE TITLE
Connection state not updating when account starts being used elsewhere.

### ISSUE THREAD

**Issue by valevalorin** [mopidy/pyspotify#186]
I want to be able to gracefully handle when a user (me) starts using Spotify on a different device. However, when monitoring the connection state, I notice that it doesn't change when I start using Spotify, from say, my phone and my program stops working (although it doesn't throw any errors). Is this a bug or is monitoring the connection state not the proper way to detect account use on other devices?

**Comment by kingosticks** [comment]
You should be listening for when the `PLAY_TOKEN_LOST`session event occurs [like mopidy-spotify does](https://github.com/mopidy/mopidy-spotify/blob/develop/mopidy_spotify/backend.py#L83-L85).

**Comment by valevalorin** [comment]
Ahh, gotcha. Thank you very much for your help!
