### ISSUE TITLE
[question] Get info on Spotify account's current state/track 

### ISSUE THREAD

**Issue by aars** [mopidy/pyspotify#187]
I'm having trouble finding an answer to this question:

Is it possible to use the Spotify API (and pyspotify) to get the current state (and currently playing track) of the account? Is it possible to see what another client is playing on the same account?

Thanks

**Comment by jodal** [comment]
I don't know about Spotify's Web APIs, but it's not possible to know if you're already playing somewhere else or what is being listened to using pyspotify/libspotify.

**Comment by aars** [comment]
Thanks!
