### ISSUE TITLE
How to set offline mode?

### ISSUE THREAD

**Issue by bphermansson** [mopidy/pyspotify#190]
I cant get this to work, I'm trying to set my app in offline mode with:

``` python
spotify.connection.Connection.allow_network = False
```

After this I expect my "connection state changed" method to be triggered, as it does when the program starts:

``` python
session.on(spotify.SessionEvent.CONNECTION_STATE_UPDATED, conn_state_change)
```

But it doesn't. How do I properly set my program in offline mode? I want to simulate how it works when no network is available.

**Comment by jodal** [comment]
You're trying to set `allow_network` attribute on the `Connection` class itself. You'll need to set it on the session object's `Connection` instance, ref the docs:

> You’ll never need to create an instance of this class yourself. You’ll find it ready to use as the connection attribute on the Session instance.

-- https://pyspotify.mopidy.com/en/latest/api/connection/#spotify.connection.Connection

Try to do it like this:

``` python
session.connection.allow_network = False
```

**Comment by bphermansson** [comment]
Ok thanks, that works!

**Comment by jodal** [comment]
Great :)
