### ISSUE TITLE
Tracks are not added to playlist

### ISSUE THREAD

**Issue by mind1m** [mopidy/pyspotify#193]
Hello,

I have encountered a bug with the adding tracks to playlist.
The code seems to work and when I restart the program to see what is the length of the playlist, it is updated correctly (+1 for each run). However, the playlist remains empty in both my desktop and web apps.

Here is a sample code:

```
import time
import spotify

# NOTE: you should have your binary libspotify key in this folder
# and libspotify installed
SPOTIFY_LOGIN = ''
SPOTIFY_PASS = ''
PLAYLIST_URI = ''

session = spotify.Session()
session.login(SPOTIFY_LOGIN, SPOTIFY_PASS)

while session.connection.state != 1:
    print('Logging in...')
    session.process_events()
    time.sleep(1)

print('Logged in as {}'.format(session.user))

playlist = session.get_playlist(PLAYLIST_URI)
playlist.load()

print('Playlist length is {}'.format(len(playlist.tracks)))

track = None
search = session.search('Hotline Bling Drake')
search.load()
if len(search.tracks):
    track = search.tracks[0].load()
else:
    raise ValueError('Track is not found')

print('Adding track...')

playlist.add_tracks(track)

while playlist.has_pending_changes:
        session.process_events()

print('Done')

session.logout()
# not sure if we need this?
while session.connection.state == 1:
    session.process_events()
    time.sleep(1)

```

OSX, python 3.5.1, pyspotify 2.0.5

**Comment by kingosticks** [comment]
Have you tried adding a call to logout of the session before you exit the program? You usually need to do this to ensure the changes are synced with Spotify server's (and not just saves to your local cache).

**Comment by mind1master** [comment]
@kingosticks I have done it now (added to the listing above) but it doesn't seem to help

**Comment by kingosticks** [comment]
Yeh, the check for pending changes should really be enough in this case. Perhaps post a full log during a run?  If this is still an issue when I'm back from holiday on the weekend I'll give the code a try myself too.

**Comment by mind1master** [comment]
Here is a log of two subsequent runs of the above code:

```
(env)~/s/spotify> python test_playlist.py
Logging in...
Logged in as User('spotify:user:XXXXXX')
Playlist length is 0
Adding track...
Logout
Done
(env)~/s/spotify> python test_playlist.py
Logging in...
Logged in as User('spotify:user:XXXXXX')
Playlist length is 1
Adding track...
Logout
Done
```

It can be seen that playlist length is increasing, but it is empty in the spotify app.
