### ISSUE TITLE
Random deadlocks during notify_main_thread() callback

### ISSUE THREAD

**Issue by jkp** [mopidy/pyspotify#86]
I didn't really know what to name this issue because the problem is actually potentially in other places but this is the one place I know it exists.  Take a look at the following backtraces:

     Thread 13
     
     (gdb) bt 10
     #0  0x9302191a in __psynch_mutexwait ()
     #1  0x98e4c13b in pthread_mutex_lock ()
     #2  0x012bc769 in g_session ()
     #3  0x012bc8bd in g_session ()
     #4  0x0132a9f7 in g_session ()
     #5  0x01331dfa in g_session ()
     #6  0x012f658f in g_session ()
     #7  0x013a6ff0 in sp_albumbrowse_create ()
     #8  0x0125d802 in AlbumBrowser_new ()
     #9  0x0008f76a in type_call (type=0x1264a98, args=0x14a6328, kwds=0x0) at Objects/typeobject.c:422
     
     Thread 12
     
     (gdb) bt
     #0  0x930218e2 in __psynch_cvwait ()
     #1  0x98e4b220 in _pthread_cond_wait ()
     #2  0x98ed10a1 in pthread_cond_wait$UNIX2003 ()
     #3  0x0012ef20 in PyThread_acquire_lock (lock=0x7a97f0e0, waitflag=1) at thread_pthread.h:452
     #4  0x000df971 in PyEval_RestoreThread (tstate=0x7c267f30) at Python/ceval.c:364
     #5  0x0011901d in PyGILState_Ensure () at Python/pystate.c:592
     #6  0x0125bb22 in notify_main_thread ()
     #7  0x012bc5eb in g_session ()
     #8  0x012dd6f7 in g_session ()
     #9  0x012d0ceb in g_session ()
     #10 0x012d47a1 in g_session ()
     #11 0x012d2dd9 in g_session ()
     #12 0x012cccf3 in g_session ()
     #13 0x012ce6c9 in g_session ()
     #14 0x0137be72 in g_session ()
     #15 0x0137be10 in g_session ()
     #16 0x0137daa9 in g_session ()
     #17 0x0137d8bf in g_session ()
     #18 0x012a1228 in g_session ()
     #19 0x98e46557 in _pthread_start ()
     #20 0x98e30cee in thread_start ()

The problem is that the Spofify notify callback is being invoked whilst the GIL is held by another thread: that thread in turn is blocking on something in g_session, which I can only assume is being held by the notify thread.

Now you could easily argue that libspotify should guarantee that this will never happen, but alas, that doesn't seem to be the case.

One possible fix for this would be to release the GIL before making a Spotify API call and re-aquire it when the call finishes.  It's not the prettiest of things but it's probably the only safe thing to do.

For what it's worth I have spent hours and hours trying to track this down - it happens extremely regularly in my application (I'm the maintainer of the Plex Spotify plugin) - I'm pretty sure this isn't the only case where this is possible.

If you agree that this is a good solution to the issue I'm happy to run up a pull-request.

**Comment by jodal** [comment]
Due to the imminent release of the 2.0 rewrite of pyspotify, this will probably never be done. Closing.
